### ISSUE TITLE
Not all non-pombe stanzas are removed by --make-species-subset

### ISSUE THREAD

**Issue by kimrutherford** [owlcollab/owltools#165] opened 2016-10-01 08:16 UTC
When I run:
  owltools --use-catalog go-plus.owl --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo go-plus-pombe-only.obo

most stanzas with restrictions like:
  relationship: only_in_taxon NCBITaxon_Union:0000004 {id="GOTAX:0000117"} ! Prokaryota

get removed, but a few don't.

There are some stanzas that remain that should be excluded because of only_in_taxon Prokaryota and one that has:
 only_in_taxon NCBITaxon_Union:0000007 {id="GOTAX:0000169"} ! Viridiplantae or Bacteria or Euglenozoa

Two examples:

[Term]
id: GO:0009291
name: unidirectional conjugation
namespace: biological_process
def: "The process of unidirectional (polarized) transfer of genetic ..." [ISBN:0387520546]
subset: gosubset_prok
synonym: "mating" BROAD []
is_a: GO:0000746 ! conjugation
is_a: GO:0009292 ! genetic transfer
relationship: only_in_taxon NCBITaxon_Union:0000004 {id="GOTAX:0000117"} ! Prokaryota

[Term]
id: GO:0009766
name: primary charge separation
namespace: biological_process
def: "In the photosynthetic reaction centers, primary charge separation is initiated by the excitation of a molecule followed by the transfer of an electron to an electron acceptor molecule f
ollowing energy transfer from light harvesting complexes." [ISBN:0792361431]
is_a: GO:0022904 ! respiratory electron transport chain
relationship: only_in_taxon NCBITaxon_Union:0000007 {id="GOTAX:0000169"} ! Viridiplantae or Bacteria or Euglenozoa
relationship: part_of GO:0019684 ! photosynthesis, light reaction

**Comment by cmungall** [comment] 2016-10-03 18:14
I see now the reasoning strategy is incomplete for union classes, 
because the disjointness transform isn't applied to these. I'll fix this 
upstream in the GO pipeline.

**Comment by fbastian** [comment] 2016-10-05 13:18
@cmungall: anything I should be worried about for taxon constraints in Bgee?

**Comment by cmungall** [comment] 2016-10-05 14:24
No we never use unions in uberon TCs

**Comment by kimrutherford** [comment] 2017-09-25 05:35
Hi.  We have the same symptom again.  I don't know if it's the same problem.

We're using this command line in go-svn/ontology/extensions/:

    owltools --use-catalog go-plus.owl --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo go-pombe-subset.obo

but lots of non-pombe stanzas are in the output.  eg.

[Term]
id: GO:0000325
name: plant-type vacuole
namespace: cellular_component
synonym: "vacuole, cell cycle-independent morphology" EXACT []
is_a: GO:0005773 ! vacuole
relationship: only_in_taxon NCBITaxon:33090 ! Viridiplantae

[Term]
id: GO:0000326
name: protein storage vacuole
namespace: cellular_component
is_a: GO:0000322 ! storage vacuole
is_a: GO:0000325 ! plant-type vacuole

Thanks,.

**Comment by ValWood** [comment] 2017-10-18 07:21
Any news on this?

**Comment by cmungall** [comment] 2017-10-18 16:21
Identified probably cause and filed a bug for myself here:
https://github.com/geneontology/go-ontology/issues/14378

**Comment by cmungall** [comment] 2017-10-19 00:19
> We're using this command line in go-svn/ontology/extensions/:

I don't recommend using svn, we use github for development but anyone should be able to use 

http://purl.obolibrary.org/obo/go/extensions/go-plus.owl without doing any kind of checkout.

OK, so I regenerated ncbitaxon_import internally, will be reflected in release at midnight

however, when I now try and run this it crashes Elk, how much memory do you have to play with here?

8hrs from now you could try something like:

```
wget http://purl.obolibrary.org/obo/go/extensions/go-plus.owl 
OWLTOOLS_MEMORY=32G owltools go-plus.owl  --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo go-pombe-subset.obo
```

sorry this is a palaver, will look at more effective ways of doing this.

**Comment by kimrutherford** [comment] 2017-10-19 00:59
> but anyone should be able to use http://purl.obolibrary.org/obo/go/extensions/go-plus.owl without doing any kind of checkout.

OK, we'll change to use that.

> how much memory do you have to play with here?

Our server has 48GB of memory but we can't use all of that because the machine does other jobs too.

> 8hrs from now you could try something like:

I just tried that command as a test and it ran OK.  I'll run it again and check the output in 8 hours from now.

Thanks for your help.

**Comment by kimrutherford** [comment] 2017-10-20 09:21
>  I'll run it again and check the output in 8 hours from now.

It finished and the non-pombe term that Val spotted has gone from the output.  We'll have a deeper look early next week to see if the rest looks OK.

It took nearly 2 hours to run on the 24 core server I borrowed for testing.  I gave Java 100GB of RAM just to be sure it finished.  I'll try again now with much less RAM.

**Comment by kimrutherford** [comment] 2017-10-21 05:29
> I gave Java 100GB of RAM just to be sure it finished.

I tried reducing OWLTOOLS_MEMORY to 80GB but it ran out of memory.

Here's the end of the log:

```
2017-10-21 04:33:57,157 INFO  (AbstractReasonerStage:161) Consistency Checking using 24 workers
2017-10-21 04:33:57,238 INFO  (LoggingStageExecutor:103) Consistency Checking took 88 ms
2017-10-21 04:33:57,239 INFO  (LoggingStageExecutor:70) Class Taxonomy Computation started
2017-10-21 04:33:57,249 INFO  (AbstractReasonerStage:161) Class Taxonomy Computation using 24 workerJava HotSpot(TM) 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGTERM to handler- the VM may need to be forcibly terminated
Exception in thread "elk-reasoner-thread-23" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elk-reasoner-thread-23"
Exception in thread "elk-reasoner-thread-9" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elk-reasoner-thread-22"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elk-reasoner-thread-9"
```

**Comment by kimrutherford** [comment] 2017-11-01 10:27
Is there any work-around we can use to reduce the memory usage?

**Comment by ValWood** [comment] 2018-01-26 21:13
Any ideas about this, I'm going through our open tickets and this is still labelled as "waiting for external change"
I tested Canto and I still see "plant type vacuole" even though we filter taxon restricted terms....

**Comment by ValWood** [comment] 2018-01-26 21:16
It isn't something to do with the redundant taxon  restrictions is it?
https://www.ebi.ac.uk/QuickGO/term/GO:0000325
@kimrutherford (at our end?)

(I can't remember how it was related to the issue here)

**Comment by kimrutherford** [comment] 2018-01-26 21:34
> It isn't something to do with the redundant taxon restrictions is it?

I don't know.

> I still see "plant type vacuole" even though we filter taxon restricted terms....

We're using the unfiltered GO OBO in Canto at the moment.  We can't run owltools to generate a taxon restricted file because it uses too much memory for our server.

**Comment by ValWood** [comment] 2018-01-26 21:43
Ah OK, I could not remember what the issue was.   I didn't realise we were not running the taxon restrictions (or I forgot).

**Comment by ValWood** [comment] 2018-01-26 21:46
It's kind of odd though, because I don't see most taxon restricted terms
 (like multicellular  process, scab formation, system process, circadian anything...)
so at some level taxon restriction is working in Canto?

**Comment by kimrutherford** [comment] 2018-01-26 22:03
We're loading http://purl.obolibrary.org/obo/go/go-basic.obo directly for now.

> because I don't see most taxon restricted terms

I just looked up circadian rhythm and "multicellular organismal process" in Canto and found them.

**Comment by ValWood** [comment] 2018-01-26 22:08
ignore. I wasn't in process...

**Comment by ValWood** [comment] 2018-02-23 20:10
@kimrutherford  we still see taxon restricted terms in Canto. Is this  problem caused by  PomBase not being able to consume taxon restrictions internally ? or something else?

I just want to check that the issue is reported in the right place.

v

**Comment by ValWood** [comment] 2018-02-23 20:12
For example, we still see this in Canto:
https://www.ebi.ac.uk/QuickGO/term/GO:0102084

**Comment by kimrutherford** [comment] 2018-02-24 11:09
> we still see taxon restricted terms in Canto. Is this problem caused by PomBase not being
> able to consume taxon restrictions internally ? or something else?

We can't run OWLTools at the moment because it uses too much memory when generating the taxon restricted OBO file.  So for now we load the whole GO go-basic into Canto.  We load this file: http://purl.obolibrary.org/obo/go/go-basic.obo

**Comment by ValWood** [comment] 2018-02-24 21:28
hmm, so  long term we need to wait for what?

**Comment by kimrutherford** [comment] 2018-02-24 21:53
@cmungall are there any workarounds we could try that could prevent OWLTools from running out of memory when we use --make-species-subset?  Or any other tools we could try that would generate a taxon restricted OBO file from GO?

**Comment by cmungall** [comment] 2018-05-31 04:30
apologies I haven't done anything in this in all this time.

One thing you could do that is really tedious is a few iterations, e.g. eukartyote->fungi->SPombe, feeding the output from each stage into the input in the next stage. This gets around the issue that Elk seems to be a massive memory hog when large numbers of classes are inferred to be unsatisfiable.

We should either build this in or rewrite, not sure if @balhoff or @fbastian have any interim suggestions.

**Comment by cmungall** [comment] 2018-05-31 04:52
Additional annoyance: there is a syntax error in one of the never-in constraints in the ontology which will throw an error. This is unrelated to the memory issue, but will be an annoyance to you

This fixes it:
https://github.com/geneontology/go-ontology/pull/15833

But won't percolate into release til tomorrow

**Comment by cmungall** [comment] 2018-05-31 04:54
ok I was able to run this on my laptop with each cycle taking a few seconds...

```
  owltools --use-catalog go-edit.obo --reasoner elk --make-species-subset -t NCBITaxon:33154 -o -f obo go-plus-Opisthokonta-only.obo
  owltools --use-catalog go-plus-Opisthokonta-only.obo --reasoner elk --make-species-subset -t NCBITaxon:4751 -o -f obo go-plus-Fungi.obo
  owltools --use-catalog go-plus-Fungi.obo --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo go-plus-pombe.obo
```

file sizes:
```
go-edit.obo:47366
go-plus-Fungi.obo:37543
go-plus-Opisthokonta-only.obo:46182
go-plus-pombe.obo:33475
```

kind of bizarre that combining into one step has such a huge effect on memory use...

**Comment by kimrutherford** [comment] 2018-05-31 06:03
> ok I was able to run this on my laptop with each cycle taking a few seconds...

Thanks for testing that.  We'll give that a go for Canto.

**Comment by cmungall** [comment] 2018-06-01 20:59
Can you also try the direct route? i.e.

```
owltools --use-catalog go-plus.owl --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo go-plus-pombe-only.obo
```

This takes seconds on my laptop now. The underling taxon algorithm has not changed, but it's possible that either there was an improvement to Elk OR there was some underlying issue in the ontology that was fixed.

In general we have found Elk to be super-efficient, it usually reasons over anything we can give it in seconds. There are corner cases that cause the procedure it uses to blow up occasionally. This could happen if something odd was leaking in from another ontology in the imports. @balhoff has been making improvements to the imports process.

**Comment by kimrutherford** [comment] 2018-06-01 23:21
Thanks Chris.  We'll give that a go.  Should we be using the master branch of owltools?

**Comment by cmungall** [comment] 2018-06-01 23:30
Yes, go ahead and use master

**Comment by kimrutherford** [comment] 2018-06-02 00:31
I've cloned and built the master branch but unfortunately I hit an error.

I used these commands:

```sh
curl -L http://purl.obolibrary.org/obo/go/extensions/go-plus.owl > /tmp/go-plus.owl
owltools --use-catalog /tmp/go-plus.owl --reasoner elk --make-species-subset -t NCBITaxon:4896 -o -f obo /tmp/go-plus-pombe-only.obo
```

And got this error:

```
2018-06-02 00:43:24,408 WARN  (ChangeIndexingProcessor:66) [reasoner.indexing.axiomIgnored]ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/RO_0002005> <http://purl.obolibrary.org/obo/RO_0002134>)

Exception in thread "main" java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.expand(MacroExpansionVisitor.java:162)
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.<init>(MacroExpansionVisitor.java:122)
        at org.obolibrary.macro.MacroExpansionVisitor.expandAll(MacroExpansionVisitor.java:95)
        at owltools.mooncat.SpeciesSubsetterUtil.<init>(SpeciesSubsetterUtil.java:139)
```

**Comment by kimrutherford** [comment] 2018-06-03 09:41
> I've cloned and built the master branch but unfortunately I hit an error.

I just tried again and now the owltools command finishes.  Maybe a problem in go-plus.owl has gone away?

Most of the non-pombe terms that we had reported earlier are now gone but unfortunately there are still some unwanted terms.  Here are two examples:

```
[Term]
id: GO:0009291
name: unidirectional conjugation
namespace: biological_process
def: "The process of unidirectional (polarized) transfer of genetic information ..." [ISBN:0387520546]
subset: gosubset_prok
synonym: "mating" BROAD []
is_a: GO:0000746 ! conjugation
is_a: GO:0009292 ! genetic transfer
relationship: only_in_taxon NCBITaxon_Union:0000004 {id="GOTAX:0000117"}
```

and

```
[Term]
id: GO:1905393
name: plant organ formation
namespace: biological_process
def: "The process that gives rise to the plant organ. ..." [GO_REF:0000081, GOC:tb, GOC:TermGenie]
is_a: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of PO:0009008 ! plant organ
relationship: results_in_formation_of PO:0009008 ! plant organ
created_by: tb
creation_date: 2016-08-24T00:21:27Z
```

Here's the file I got from owltools:
  https://curation.pombase.org/kmr44/go-plus-pombe-only.obo

Thanks.

**Comment by ValWood** [comment] 2018-06-28 10:28
can close?

**Comment by kimrutherford** [comment] 2018-06-29 05:13
> can close?

The pombe taxon restricted go-plus still contains "unidirectional conjugation" and "plant organ formation".

**Comment by ValWood** [comment] 2018-06-29 05:32
"plant organ formation"
doesn't appear to have a taxon restriction, I will request one.
https://www.ebi.ac.uk/QuickGO/term/GO:1905393

"unidirectional conjugation" has though.
This is odd because we don't get all the taxon restricted terms do we? What's different about this one?

has
GO:0009291 | unidirectional conjugation | Only in Taxon | 2, 2157 | Prokaryota

are we ignoring "only in" but including "never in"?

**Comment by ValWood** [comment] 2018-07-02 06:06
check tomorrow:
https://github.com/geneontology/go-ontology/issues/15969#issuecomment-401626655

**Comment by kimrutherford** [comment] 2018-07-03 08:02
I've ust tried owltools on from the purl go-plus.owl.  "plant organ formation" has gone but "unidirectional conjugation" is still there after taxon restriction.

**Comment by ValWood** [comment] 2018-07-03 08:14
@cmungall ?

**Comment by balhoff** [comment] 2018-07-04 01:57
@cmungall it seems that `go-taxon-groupings.owl` is not imported into go-plus. Should I add it?

**Comment by cmungall** [comment] 2018-07-06 18:29
@balhoff go ahead, thanks

**Comment by balhoff** [comment] 2018-07-06 18:59
This is merged now, so we're waiting for a GO snapshot to be released. Then I would be interested to know if the issues are corrected.

**Comment by ValWood** [comment] 2018-07-06 19:11
I still see
https://www.ebi.ac.uk/QuickGO/term/GO:0009291
in Canto

even though it is "only in bacteria"

Let me know when the update is released. I should be able to check 24 hours later if this is fixed.

Val

**Comment by ValWood** [comment] 2018-07-10 19:10
It was!!!! can close. 

thanks!

**Comment by cmungall** [comment] 2018-07-10 23:49
Thanks @balhoff! 

apologies for the very long duration of this ticket

**Closed by cmungall** 2018-07-10 23:49 UTC

**Comment by ValWood** [comment] 2018-07-11 06:06
Not a problem, it wasn't a show stopper but useful to have the taxon restrictions working.

**Comment by wkpalan** [comment] 2019-05-08 15:07
Could someone please tell me whether make-species-subset or make-taxon-subset is a better command to use for creating kingdom specific obo files from go-plus.owl..

**Comment by balhoff** [comment] 2019-05-08 15:23
@wkpalan I'm not sure of the answer, but please open a new ticket rather than adding a reply to this one. Thanks!
